# Generated by Django 6.0.4 on 2026-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='video_call_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
